spring.application.name=ProfitMint

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/profitmint_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Configuration
server.port=8081
server.servlet.context-path=/api

# Session Configuration
app.session.cookie-name=PROFITMINT_SESSION
app.session.remember-me-duration-days=30

# Logging
logging.level.com.ProfitMint=DEBUG
logging.level.org.springframework.security=DEBUG
